### PR TITLE
Modify number variables

### PR DESCRIPTION
**Pull request by aparlato**
Exports a new function to modify variables that are numbers.

Supports the following operations: `*`, `/`, `+`, `-`.
Also added support for passing optional options object to round the modified value in different ways:
- `floor`: boolean
- `ceil`: boolean
- `round`: boolean
- `toFixed`: number

In usage, this function is exported and used to wrap your variables in the template file:
```
// style-template.js
const { mergeVariables, modifyNumberVariables } = require('mapbox-gl-style-build');

const textSizes = require('../variables/textSizes');

module.exports.context = {
  textSizes: modifyNumberVariables(mergeVariables(textSizes, {}), '*', 2, { round: true }),
  ...
};
```

@kelsey-taylor @ebrelsford let me know if this is not how you were thinking about this!

### CODE REVIEW

**Comment by kelsey-taylor** [comment]
thanks @aparlato! for clarification - in the example you gave, all variables in `textSizes` would be *2 in the output, right? is there any way to modify some variables in `textSizes` but not all of them uniformly?

**Review by ebrelsford — CHANGES_REQUESTED** [review]
Small test ask here at your discretion.

Could we add some simple documentation for this to the `README`?

**Comment by aparlato** [comment]
Thanks for the feedback folks!

> thanks @aparlato! for clarification - in the example you gave, all variables in textSizes would be *2 in the output, right? is there any way to modify some variables in textSizes but not all of them uniformly?

> @aparlato I wonder if you'd be open to adding a way to do this with one literal/expression (if the variables parameter is not an object treat it as a literal or expression)? Then you could do this:

This is already the current behavior, but I had bad JSDocs in there regarding type allowed so I just updated that and also added tests for passing in literal values and expression values. Any of your examples should work fine!

Also updated the README with information on helper functions. Back to you all!

**Review by ebrelsford — APPROVED** [review]
Great!

**Pull request merged**
